package com.tscp.mvne.jms.request.network;

public enum NetworkRequestType {
  ACTIVATION, DEACTIVATION, REACTIVATION, DISCONNECT, SUSPEND, RESTORE, RESERVE_AND_ACTIVATE, CREATE_SERVICE, REINSTALL_SERVICE, REMOVE_SERVICE
}